language: node_js
node_js:
- 6.0.0
sudo: false
notifications:
  slack: zirateam:rmEf4yIGv0bihKpnWIZDhySs
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: botframeworkdeis